backend:
  name: github
  repo: urbain7/sandy-shop # REMPLACE CECI PAR : ton-pseudo/nom-du-repo-boutique
  branch: main

media_folder: "assets/img" # OÃ¹ les photos seront stockÃ©es
public_folder: "/assets/img"

# Configuration de l'interface
site_url: "https://urbain7.github.io/sandy-shop"
display_url: "https://urbain7.github.io/sandy-shop"
logo_url: "https://img.icons8.com/color/96/shop.png"

collections:
  - name: "produits"
    label: "ðŸ›’ Mes Produits"
    editor:
      preview: false
    # On dit Ã  Sveltia de modifier ce fichier spÃ©cifique
    files:
      - name: "catalogue"
        label: "Catalogue Complet"
        file: "data/produits.json" # Le fichier JSON que ton site Area lit
        fields:
          - name: "items"
            label: "Liste des Produits"
            widget: "list"
            summary: "{{fields.nom}} - {{fields.prix}} F"
            fields:
              - { label: "ID Unique", name: "id", widget: "uuid" }
              - { label: "Nom du produit", name: "nom", widget: "string" }
              - { label: "Prix (CFA)", name: "prix", widget: "number" }
              - { label: "Prix Original (Optionnel)", name: "prix_original", widget: "number", required: false }
              - { label: "Photo", name: "image", widget: "image" }
              - { label: "Description", name: "desc", widget: "text" }
              - { label: "Mettre en Star ?", name: "is_star", widget: "boolean", default: false }
              - { label: "Est-ce Nouveau ?", name: "is_new", widget: "boolean", default: true }
