backend:
  name: github
  repo: dataprojetconstructor/sandy-shop  # Ton nom d'utilisateur / nom du dossier
  branch: main

# Configuration des Images (SANS le slash au d√©but pour √©viter les bugs)
media_folder: "assets/img"
public_folder: "assets/img"

# Configuration de l'affichage
site_url: "https://dataprojetconstructor.github.io/sandy-shop"
display_url: "https://dataprojetconstructor.github.io/sandy-shop"
logo_url: "https://img.icons8.com/color/96/shop.png"

collections:
  - name: "produits"
    label: "üõí Mes Produits"
    editor:
      preview: false
    files:
      - name: "catalogue"
        label: "Catalogue Complet"
        file: "data/produits.json"
        fields:
          - name: "items"
            label: "Liste des Produits"
            widget: "list"
            summary: "{{fields.nom}} - {{fields.prix}} F"
            fields:
              # Identifiant Unique (G√©n√©r√© auto)
              - { label: "ID Unique", name: "id", widget: "uuid" }
              
              # Infos de base
              - { label: "Nom du produit", name: "nom", widget: "string" }
              - { label: "Prix Actuel (CFA)", name: "prix", widget: "number" }
              
              # Promo (Si rempli, le prix actuel clignote)
              - { label: "Prix Original (Optionnel - Pour promo)", name: "prix_original", widget: "number", required: false, hint: "Mettez le prix barr√© ici" }
              
              # Images
              - { label: "Image Principale", name: "image", widget: "image" }
              
              - label: "Galerie Photos (Optionnel)"
                name: "gallery"
                widget: "list"
                summary: "Photo suppl√©mentaire"
                fields:
                  - { label: "Photo", name: "img", widget: "image" }

              # Tailles
              - { label: "Tailles disponibles", name: "sizes", widget: "string", required: false, hint: "Ex: 38, 40, 42 ou S, M, L (S√©parer par des virgules)" }

              # D√©tails
              - { label: "Description", name: "desc", widget: "text" }
              
              # Options
              - { label: "Est-ce Nouveau ?", name: "is_new", widget: "boolean", default: true }
              - { label: "Mettre en Star (Accueil) ?", name: "is_star", widget: "boolean", default: false }
